version: '3'
services:
#mssql docker
  moveme-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - movemenet

  moveme-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:Connection=Server=moveme-sql,1433;Database=MoveMeDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 51886:80
    networks:
      - movemenet      
    links:
      - moveme-sql
    depends_on:
      - moveme-sql
      
networks:
  movemenet:
    driver: bridge  